name: Cake File
description: Execute a Cake file
inputs:
  file:
    type: string
    description: The cake file to execute, defaults to `cake.cs`.
    default: cake.cs
  target:
    type: string
    required: true
    description: The target that will be passed to cake as a `target` argument.
runs:
  using: composite
  steps:
  - name: Cake File
    shell: bash
    run: dotnet run ${{ inputs.file }} -c Release -- --target ${{ inputs.target }}
